apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  selector:
    matchLabels:
      app: react-app
      region: primary
  template:
    metadata:
      labels:
        app: react-app
        region: primary
    spec:
      containers:
      - name: react-app
        image: bradmccoydev/demo:primary
        env:
        - name: REACT_APP_REGION
          value: "AUS"
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  selector:
    app: react-app
    region: primary
  ports:
  - port: 80
    targetPort: 80

